# fly.toml app configuration file generated for lynkmi-api-crimson-lake-4132 on 2025-01-20T19:28:24-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lynkmi-api'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
